//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public string GUID { get; set; }
        public string DocNo { get; set; }
        public string DocTitle { get; set; }
        public double Version { get; set; }
        public System.DateTime EffDate { get; set; }
        public string FileName { get; set; }
        public long FileSize { get; set; }
        public string Remark { get; set; }
        public string ProjectId { get; set; }
    }
}
