//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAndSubFunctionView
    {
        public string ProjectNo { get; set; }
        public long SubFunctionId { get; set; }
        public string SubFunctionName { get; set; }
        public string ProjectName { get; set; }
        public string UserEmail { get; set; }
        public long MainFunctionId { get; set; }
        public Nullable<long> ParentFunctionId { get; set; }
    }
}
